# Config format schema number
format_version: 4

###################
## Model options
model_params:
  model_architecture: "resnet50"

  history_num_frames: 10
  future_num_frames: 50
  step_time: 0.1

###################
## Agent selection options
agent_select_params:
  filter_type: "vehicle"
  speed_thresh: 2.0

###################
## Input raster parameters
raster_params:
  # raster image size [pixels]
  raster_size:
    - 500 # 50 m
    - 500 
  # raster's spatial resolution [meters per pixel]: the size in the real world one pixel corresponds to.
  pixel_size:
    - 0.1 # 10 cm resolution
    - 0.1
  # From 0 to 1 per axis, [0.5,0.5] would show the ego centered in the image.
  ego_center:
    - 0.2 # 10 m behind, 40 in front
    - 0.5 # +/- 25 m on the sides
  # This is with respect to history_num_frames above and 1-indexed s.t. index N = N frames before.
  frames_to_plot:
    - 2  # 0.2 s before
    - 6  # 0.6 s before
    - 10 # 1.0 s before  
  map_type: "py_semantic_vg"

  # the keys are relative to the dataset environment variable
  satellite_map_key: "aerial_map/aerial_map.png"
  semantic_map_key: "semantic_map/semantic_map.pb"
  dataset_meta_key: "meta.json"

  # e.g. 0.0 include every obstacle, 0.5 show those obstacles with >0.5 probability of being
  # one of the classes we care about (cars, bikes, peds, etc.), >=1.0 filter all other agents.
  filter_agents_threshold: 0.8

  # whether to completely disable traffic light faces in the semantic rasterizer
  disable_traffic_light_faces: False

  # When set to True, the rasterizer will set the raster origin at bottom left,
  # i.e. vehicles are driving on the right side of the road.
  # With this change, the vertical flipping on the raster used in the visualization code is no longer needed.
  # Set it to False for models trained before v1.1.0-25-g3c517f0 (December 2020).
  # In that case visualisation will be flipped (we've removed the flip there) but the model's input will be correct.
  set_origin_to_bottom: True

###################
## Data loader options
train_data_loader:
  key: "scenes/train.zarr"
  batch_size: 16
  shuffle: True
  num_workers: 16

val_data_loader:
  key: "scenes/validate.zarr"
  batch_size: 16
  shuffle: False
  num_workers: 16

###################
## Train params
train_params:
  checkpoint_every_n_steps: 10000
  max_num_steps: 10000
  eval_every_n_steps: 10000
